/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DammamPreviewRouteImport } from './routes/dammam-preview'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as AdminShowcaseRouteImport } from './routes/admin.showcase'
import { Route as ApiPublicDriveImageFileIdRouteImport } from './routes/api/public/drive-image.$fileId'

const DammamPreviewRoute = DammamPreviewRouteImport.update({
  id: '/dammam-preview',
  path: '/dammam-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShowcaseRoute = AdminShowcaseRouteImport.update({
  id: '/admin/showcase',
  path: '/admin/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDriveImageFileIdRoute =
  ApiPublicDriveImageFileIdRouteImport.update({
    id: '/api/public/drive-image/$fileId',
    path: '/api/public/drive-image/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dammam-preview': typeof DammamPreviewRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/drive-image/$fileId': typeof ApiPublicDriveImageFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dammam-preview': typeof DammamPreviewRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/drive-image/$fileId': typeof ApiPublicDriveImageFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dammam-preview': typeof DammamPreviewRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/drive-image/$fileId': typeof ApiPublicDriveImageFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dammam-preview'
    | '/admin/showcase'
    | '/projects/$slug'
    | '/api/public/drive-image/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dammam-preview'
    | '/admin/showcase'
    | '/projects/$slug'
    | '/api/public/drive-image/$fileId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dammam-preview'
    | '/admin/showcase'
    | '/projects/$slug'
    | '/api/public/drive-image/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DammamPreviewRoute: typeof DammamPreviewRoute
  AdminShowcaseRoute: typeof AdminShowcaseRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ApiPublicDriveImageFileIdRoute: typeof ApiPublicDriveImageFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dammam-preview': {
      id: '/dammam-preview'
      path: '/dammam-preview'
      fullPath: '/dammam-preview'
      preLoaderRoute: typeof DammamPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/showcase': {
      id: '/admin/showcase'
      path: '/admin/showcase'
      fullPath: '/admin/showcase'
      preLoaderRoute: typeof AdminShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/drive-image/$fileId': {
      id: '/api/public/drive-image/$fileId'
      path: '/api/public/drive-image/$fileId'
      fullPath: '/api/public/drive-image/$fileId'
      preLoaderRoute: typeof ApiPublicDriveImageFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DammamPreviewRoute: DammamPreviewRoute,
  AdminShowcaseRoute: AdminShowcaseRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ApiPublicDriveImageFileIdRoute: ApiPublicDriveImageFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
