/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MediaRouteImport } from './routes/media'
import { Route as DammamPreviewRouteImport } from './routes/dammam-preview'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsTidaraTowersRouteImport } from './routes/projects.tidara-towers'
import { Route as ProjectsSultanatAlSharqRouteImport } from './routes/projects.sultanat-al-sharq'
import { Route as ProjectsRabiaRoadRouteImport } from './routes/projects.rabia-road'
import { Route as ProjectsRabiaMakkahRouteImport } from './routes/projects.rabia-makkah'
import { Route as ProjectsHailWalkwayRouteImport } from './routes/projects.hail-walkway'
import { Route as ProjectsHailCornicheRouteImport } from './routes/projects.hail-corniche'
import { Route as ProjectsDammamOlympicCityRouteImport } from './routes/projects.dammam-olympic-city'
import { Route as ProjectsAlshubailyNewBeachRouteImport } from './routes/projects.alshubaily-new-beach'
import { Route as ProjectsAlshubailyHighRiseRouteImport } from './routes/projects.alshubaily-high-rise'
import { Route as ProjectsAlZahraaRouteImport } from './routes/projects.al-zahraa'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as AdminShowcaseRouteImport } from './routes/admin.showcase'
import { Route as ApiPublicDriveImageFileIdRouteImport } from './routes/api/public/drive-image.$fileId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const DammamPreviewRoute = DammamPreviewRouteImport.update({
  id: '/dammam-preview',
  path: '/dammam-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTidaraTowersRoute = ProjectsTidaraTowersRouteImport.update({
  id: '/projects/tidara-towers',
  path: '/projects/tidara-towers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSultanatAlSharqRoute = ProjectsSultanatAlSharqRouteImport.update({
  id: '/projects/sultanat-al-sharq',
  path: '/projects/sultanat-al-sharq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRabiaRoadRoute = ProjectsRabiaRoadRouteImport.update({
  id: '/projects/rabia-road',
  path: '/projects/rabia-road',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRabiaMakkahRoute = ProjectsRabiaMakkahRouteImport.update({
  id: '/projects/rabia-makkah',
  path: '/projects/rabia-makkah',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsHailWalkwayRoute = ProjectsHailWalkwayRouteImport.update({
  id: '/projects/hail-walkway',
  path: '/projects/hail-walkway',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsHailCornicheRoute = ProjectsHailCornicheRouteImport.update({
  id: '/projects/hail-corniche',
  path: '/projects/hail-corniche',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDammamOlympicCityRoute =
  ProjectsDammamOlympicCityRouteImport.update({
    id: '/projects/dammam-olympic-city',
    path: '/projects/dammam-olympic-city',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsAlshubailyNewBeachRoute =
  ProjectsAlshubailyNewBeachRouteImport.update({
    id: '/projects/alshubaily-new-beach',
    path: '/projects/alshubaily-new-beach',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsAlshubailyHighRiseRoute =
  ProjectsAlshubailyHighRiseRouteImport.update({
    id: '/projects/alshubaily-high-rise',
    path: '/projects/alshubaily-high-rise',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsAlZahraaRoute = ProjectsAlZahraaRouteImport.update({
  id: '/projects/al-zahraa',
  path: '/projects/al-zahraa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShowcaseRoute = AdminShowcaseRouteImport.update({
  id: '/admin/showcase',
  path: '/admin/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDriveImageFileIdRoute =
  ApiPublicDriveImageFileIdRouteImport.update({
    id: '/api/public/drive-image/$fileId',
    path: '/api/public/drive-image/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dammam-preview': typeof DammamPreviewRoute
  '/media': typeof MediaRoute
  '/services': typeof ServicesRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/al-zahraa': typeof ProjectsAlZahraaRoute
  '/projects/alshubaily-high-rise': typeof ProjectsAlshubailyHighRiseRoute
  '/projects/alshubaily-new-beach': typeof ProjectsAlshubailyNewBeachRoute
  '/projects/dammam-olympic-city': typeof ProjectsDammamOlympicCityRoute
  '/projects/hail-corniche': typeof ProjectsHailCornicheRoute
  '/projects/hail-walkway': typeof ProjectsHailWalkwayRoute
  '/projects/rabia-makkah': typeof ProjectsRabiaMakkahRoute
  '/projects/rabia-road': typeof ProjectsRabiaRoadRoute
  '/projects/sultanat-al-sharq': typeof ProjectsSultanatAlSharqRoute
  '/projects/tidara-towers': typeof ProjectsTidaraTowersRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/drive-image/$fileId': typeof ApiPublicDriveImageFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dammam-preview': typeof DammamPreviewRoute
  '/media': typeof MediaRoute
  '/services': typeof ServicesRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/al-zahraa': typeof ProjectsAlZahraaRoute
  '/projects/alshubaily-high-rise': typeof ProjectsAlshubailyHighRiseRoute
  '/projects/alshubaily-new-beach': typeof ProjectsAlshubailyNewBeachRoute
  '/projects/dammam-olympic-city': typeof ProjectsDammamOlympicCityRoute
  '/projects/hail-corniche': typeof ProjectsHailCornicheRoute
  '/projects/hail-walkway': typeof ProjectsHailWalkwayRoute
  '/projects/rabia-makkah': typeof ProjectsRabiaMakkahRoute
  '/projects/rabia-road': typeof ProjectsRabiaRoadRoute
  '/projects/sultanat-al-sharq': typeof ProjectsSultanatAlSharqRoute
  '/projects/tidara-towers': typeof ProjectsTidaraTowersRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/public/drive-image/$fileId': typeof ApiPublicDriveImageFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dammam-preview': typeof DammamPreviewRoute
  '/media': typeof MediaRoute
  '/services': typeof ServicesRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/al-zahraa': typeof ProjectsAlZahraaRoute
  '/projects/alshubaily-high-rise': typeof ProjectsAlshubailyHighRiseRoute
  '/projects/alshubaily-new-beach': typeof ProjectsAlshubailyNewBeachRoute
  '/projects/dammam-olympic-city': typeof ProjectsDammamOlympicCityRoute
  '/projects/hail-corniche': typeof ProjectsHailCornicheRoute
  '/projects/hail-walkway': typeof ProjectsHailWalkwayRoute
  '/projects/rabia-makkah': typeof ProjectsRabiaMakkahRoute
  '/projects/rabia-road': typeof ProjectsRabiaRoadRoute
  '/projects/sultanat-al-sharq': typeof ProjectsSultanatAlSharqRoute
  '/projects/tidara-towers': typeof ProjectsTidaraTowersRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/drive-image/$fileId': typeof ApiPublicDriveImageFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dammam-preview'
    | '/media'
    | '/services'
    | '/admin/showcase'
    | '/projects/$slug'
    | '/projects/al-zahraa'
    | '/projects/alshubaily-high-rise'
    | '/projects/alshubaily-new-beach'
    | '/projects/dammam-olympic-city'
    | '/projects/hail-corniche'
    | '/projects/hail-walkway'
    | '/projects/rabia-makkah'
    | '/projects/rabia-road'
    | '/projects/sultanat-al-sharq'
    | '/projects/tidara-towers'
    | '/projects/'
    | '/api/public/drive-image/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dammam-preview'
    | '/media'
    | '/services'
    | '/admin/showcase'
    | '/projects/$slug'
    | '/projects/al-zahraa'
    | '/projects/alshubaily-high-rise'
    | '/projects/alshubaily-new-beach'
    | '/projects/dammam-olympic-city'
    | '/projects/hail-corniche'
    | '/projects/hail-walkway'
    | '/projects/rabia-makkah'
    | '/projects/rabia-road'
    | '/projects/sultanat-al-sharq'
    | '/projects/tidara-towers'
    | '/projects'
    | '/api/public/drive-image/$fileId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dammam-preview'
    | '/media'
    | '/services'
    | '/admin/showcase'
    | '/projects/$slug'
    | '/projects/al-zahraa'
    | '/projects/alshubaily-high-rise'
    | '/projects/alshubaily-new-beach'
    | '/projects/dammam-olympic-city'
    | '/projects/hail-corniche'
    | '/projects/hail-walkway'
    | '/projects/rabia-makkah'
    | '/projects/rabia-road'
    | '/projects/sultanat-al-sharq'
    | '/projects/tidara-towers'
    | '/projects/'
    | '/api/public/drive-image/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DammamPreviewRoute: typeof DammamPreviewRoute
  MediaRoute: typeof MediaRoute
  ServicesRoute: typeof ServicesRoute
  AdminShowcaseRoute: typeof AdminShowcaseRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsAlZahraaRoute: typeof ProjectsAlZahraaRoute
  ProjectsAlshubailyHighRiseRoute: typeof ProjectsAlshubailyHighRiseRoute
  ProjectsAlshubailyNewBeachRoute: typeof ProjectsAlshubailyNewBeachRoute
  ProjectsDammamOlympicCityRoute: typeof ProjectsDammamOlympicCityRoute
  ProjectsHailCornicheRoute: typeof ProjectsHailCornicheRoute
  ProjectsHailWalkwayRoute: typeof ProjectsHailWalkwayRoute
  ProjectsRabiaMakkahRoute: typeof ProjectsRabiaMakkahRoute
  ProjectsRabiaRoadRoute: typeof ProjectsRabiaRoadRoute
  ProjectsSultanatAlSharqRoute: typeof ProjectsSultanatAlSharqRoute
  ProjectsTidaraTowersRoute: typeof ProjectsTidaraTowersRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicDriveImageFileIdRoute: typeof ApiPublicDriveImageFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dammam-preview': {
      id: '/dammam-preview'
      path: '/dammam-preview'
      fullPath: '/dammam-preview'
      preLoaderRoute: typeof DammamPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/tidara-towers': {
      id: '/projects/tidara-towers'
      path: '/projects/tidara-towers'
      fullPath: '/projects/tidara-towers'
      preLoaderRoute: typeof ProjectsTidaraTowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/sultanat-al-sharq': {
      id: '/projects/sultanat-al-sharq'
      path: '/projects/sultanat-al-sharq'
      fullPath: '/projects/sultanat-al-sharq'
      preLoaderRoute: typeof ProjectsSultanatAlSharqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/rabia-road': {
      id: '/projects/rabia-road'
      path: '/projects/rabia-road'
      fullPath: '/projects/rabia-road'
      preLoaderRoute: typeof ProjectsRabiaRoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/rabia-makkah': {
      id: '/projects/rabia-makkah'
      path: '/projects/rabia-makkah'
      fullPath: '/projects/rabia-makkah'
      preLoaderRoute: typeof ProjectsRabiaMakkahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/hail-walkway': {
      id: '/projects/hail-walkway'
      path: '/projects/hail-walkway'
      fullPath: '/projects/hail-walkway'
      preLoaderRoute: typeof ProjectsHailWalkwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/hail-corniche': {
      id: '/projects/hail-corniche'
      path: '/projects/hail-corniche'
      fullPath: '/projects/hail-corniche'
      preLoaderRoute: typeof ProjectsHailCornicheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/dammam-olympic-city': {
      id: '/projects/dammam-olympic-city'
      path: '/projects/dammam-olympic-city'
      fullPath: '/projects/dammam-olympic-city'
      preLoaderRoute: typeof ProjectsDammamOlympicCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/alshubaily-new-beach': {
      id: '/projects/alshubaily-new-beach'
      path: '/projects/alshubaily-new-beach'
      fullPath: '/projects/alshubaily-new-beach'
      preLoaderRoute: typeof ProjectsAlshubailyNewBeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/alshubaily-high-rise': {
      id: '/projects/alshubaily-high-rise'
      path: '/projects/alshubaily-high-rise'
      fullPath: '/projects/alshubaily-high-rise'
      preLoaderRoute: typeof ProjectsAlshubailyHighRiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/al-zahraa': {
      id: '/projects/al-zahraa'
      path: '/projects/al-zahraa'
      fullPath: '/projects/al-zahraa'
      preLoaderRoute: typeof ProjectsAlZahraaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/showcase': {
      id: '/admin/showcase'
      path: '/admin/showcase'
      fullPath: '/admin/showcase'
      preLoaderRoute: typeof AdminShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/drive-image/$fileId': {
      id: '/api/public/drive-image/$fileId'
      path: '/api/public/drive-image/$fileId'
      fullPath: '/api/public/drive-image/$fileId'
      preLoaderRoute: typeof ApiPublicDriveImageFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DammamPreviewRoute: DammamPreviewRoute,
  MediaRoute: MediaRoute,
  ServicesRoute: ServicesRoute,
  AdminShowcaseRoute: AdminShowcaseRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsAlZahraaRoute: ProjectsAlZahraaRoute,
  ProjectsAlshubailyHighRiseRoute: ProjectsAlshubailyHighRiseRoute,
  ProjectsAlshubailyNewBeachRoute: ProjectsAlshubailyNewBeachRoute,
  ProjectsDammamOlympicCityRoute: ProjectsDammamOlympicCityRoute,
  ProjectsHailCornicheRoute: ProjectsHailCornicheRoute,
  ProjectsHailWalkwayRoute: ProjectsHailWalkwayRoute,
  ProjectsRabiaMakkahRoute: ProjectsRabiaMakkahRoute,
  ProjectsRabiaRoadRoute: ProjectsRabiaRoadRoute,
  ProjectsSultanatAlSharqRoute: ProjectsSultanatAlSharqRoute,
  ProjectsTidaraTowersRoute: ProjectsTidaraTowersRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicDriveImageFileIdRoute: ApiPublicDriveImageFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
